// Generated by scripts/build_asset_catalog.py. Do not edit by hand.
window.WorldZooAssetCatalog = {
  "hawk": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_37 (1).png",
    "color": "assets/animals/color/animal_hawk_color.webp",
    "stone": "assets/animals/stone/animal_hawk_stone.webp"
  },
  "peacock": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_37 (2).png",
    "color": "assets/animals/color/animal_peacock_color.webp",
    "stone": "assets/animals/stone/animal_peacock_stone.webp"
  },
  "ostrich": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_37 (3).png",
    "color": "assets/animals/color/animal_ostrich_color.webp",
    "stone": "assets/animals/stone/animal_ostrich_stone.webp"
  },
  "crow": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_54 (1).png",
    "color": "assets/animals/color/animal_crow_color.webp",
    "stone": "assets/animals/stone/animal_crow_stone.webp"
  },
  "chicken": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_54 (2).png",
    "color": "assets/animals/color/animal_chicken_color.webp",
    "stone": "assets/animals/stone/animal_chicken_stone.webp"
  },
  "eagle": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (10).png",
    "color": "assets/animals/color/animal_eagle_color.webp",
    "stone": "assets/animals/stone/animal_eagle_stone.webp"
  },
  "duck": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (3).png",
    "color": "assets/animals/color/animal_duck_color.webp",
    "stone": "assets/animals/stone/animal_duck_stone.webp"
  },
  "goose": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (4).png",
    "color": "assets/animals/color/animal_goose_color.webp",
    "stone": "assets/animals/stone/animal_goose_stone.webp"
  },
  "swallow": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (5).png",
    "color": "assets/animals/color/animal_swallow_color.webp",
    "stone": "assets/animals/stone/animal_swallow_stone.webp"
  },
  "swan": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (6).png",
    "color": "assets/animals/color/animal_swan_color.webp",
    "stone": "assets/animals/stone/animal_swan_stone.webp"
  },
  "parrot": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (7).png",
    "color": "assets/animals/color/animal_parrot_color.webp",
    "stone": "assets/animals/stone/animal_parrot_stone.webp"
  },
  "budgerigar": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (8).png",
    "color": "assets/animals/color/animal_budgerigar_color.webp",
    "stone": "assets/animals/stone/animal_budgerigar_stone.webp"
  },
  "owl": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_54_55 (9).png",
    "color": "assets/animals/color/animal_owl_color.webp",
    "stone": "assets/animals/stone/animal_owl_stone.webp"
  },
  "koala": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_16 (1).png",
    "color": "assets/animals/color/animal_koala_color.webp",
    "stone": "assets/animals/stone/animal_koala_stone.webp"
  },
  "kangaroo": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_16 (2).png",
    "color": "assets/animals/color/animal_kangaroo_color.webp",
    "stone": "assets/animals/stone/animal_kangaroo_stone.webp"
  },
  "sheep": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_16 (3).png",
    "color": "assets/animals/color/animal_sheep_color.webp",
    "stone": "assets/animals/stone/animal_sheep_stone.webp"
  },
  "goat": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_16 (4).png",
    "color": "assets/animals/color/animal_goat_color.webp",
    "stone": "assets/animals/stone/animal_goat_stone.webp"
  },
  "cow": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_16 (5).png",
    "color": "assets/animals/color/animal_cow_color.webp",
    "stone": "assets/animals/stone/animal_cow_stone.webp"
  },
  "pigeon": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_17 (10).png",
    "color": "assets/animals/color/animal_pigeon_color.webp",
    "stone": "assets/animals/stone/animal_pigeon_stone.webp"
  },
  "pig": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_17 (6).png",
    "color": "assets/animals/color/animal_pig_color.webp",
    "stone": "assets/animals/stone/animal_pig_stone.webp"
  },
  "monkey": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_17 (7).png",
    "color": "assets/animals/color/animal_monkey_color.webp",
    "stone": "assets/animals/stone/animal_monkey_stone.webp"
  },
  "platypus": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_17 (8).png",
    "color": "assets/animals/color/animal_platypus_color.webp",
    "stone": "assets/animals/stone/animal_platypus_stone.webp"
  },
  "sparrow": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_17 (9).png",
    "color": "assets/animals/color/animal_sparrow_color.webp",
    "stone": "assets/animals/stone/animal_sparrow_stone.webp"
  },
  "dog": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_39 (1).png",
    "color": "assets/animals/color/animal_dog_color.webp",
    "stone": "assets/animals/stone/animal_dog_stone.webp"
  },
  "hamster": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_39 (2).png",
    "color": "assets/animals/color/animal_hamster_color.webp",
    "stone": "assets/animals/stone/animal_hamster_stone.webp"
  },
  "sloth": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_39 (3).png",
    "color": "assets/animals/color/animal_sloth_color.webp",
    "stone": "assets/animals/stone/animal_sloth_stone.webp"
  },
  "hippo": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (10).png",
    "color": "assets/animals/color/animal_hippo_color.webp",
    "stone": "assets/animals/stone/animal_hippo_stone.webp"
  },
  "armadillo": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (4).png",
    "color": "assets/animals/color/animal_armadillo_color.webp",
    "stone": "assets/animals/stone/animal_armadillo_stone.webp"
  },
  "giraffe": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (5).png",
    "color": "assets/animals/color/animal_giraffe_color.webp",
    "stone": "assets/animals/stone/animal_giraffe_stone.webp"
  },
  "tiger": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (6).png",
    "color": "assets/animals/color/animal_tiger_color.webp",
    "stone": "assets/animals/stone/animal_tiger_stone.webp"
  },
  "gorilla": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (7).png",
    "color": "assets/animals/color/animal_gorilla_color.webp",
    "stone": "assets/animals/stone/animal_gorilla_stone.webp"
  },
  "zebra": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (8).png",
    "color": "assets/animals/color/animal_zebra_color.webp",
    "stone": "assets/animals/stone/animal_zebra_stone.webp"
  },
  "rhinoceros": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_40 (9).png",
    "color": "assets/animals/color/animal_rhinoceros_color.webp",
    "stone": "assets/animals/stone/animal_rhinoceros_stone.webp"
  },
  "bear": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_56 (1).png",
    "color": "assets/animals/color/animal_bear_color.webp",
    "stone": "assets/animals/stone/animal_bear_stone.webp"
  },
  "raccoon_dog": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_56 (2).png",
    "color": "assets/animals/color/animal_raccoon_dog_color.webp",
    "stone": "assets/animals/stone/animal_raccoon_dog_stone.webp"
  },
  "red_panda": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (10).png",
    "color": "assets/animals/color/animal_red_panda_color.webp",
    "stone": "assets/animals/stone/animal_red_panda_stone.webp"
  },
  "deer": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (3).png",
    "color": "assets/animals/color/animal_deer_color.webp",
    "stone": "assets/animals/stone/animal_deer_stone.webp"
  },
  "wolf": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (4).png",
    "color": "assets/animals/color/animal_wolf_color.webp",
    "stone": "assets/animals/stone/animal_wolf_stone.webp"
  },
  "squirrel": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (5).png",
    "color": "assets/animals/color/animal_squirrel_color.webp",
    "stone": "assets/animals/stone/animal_squirrel_stone.webp"
  },
  "hedgehog": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (6).png",
    "color": "assets/animals/color/animal_hedgehog_color.webp",
    "stone": "assets/animals/stone/animal_hedgehog_stone.webp"
  },
  "mole": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (7).png",
    "color": "assets/animals/color/animal_mole_color.webp",
    "stone": "assets/animals/stone/animal_mole_stone.webp"
  },
  "mouse": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (8).png",
    "color": "assets/animals/color/animal_mouse_color.webp",
    "stone": "assets/animals/stone/animal_mouse_stone.webp"
  },
  "guinea_pig": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_55_57 (9).png",
    "color": "assets/animals/color/animal_guinea_pig_color.webp",
    "stone": "assets/animals/stone/animal_guinea_pig_stone.webp"
  },
  "fox": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_56_14 (1).png",
    "color": "assets/animals/color/animal_fox_color.webp",
    "stone": "assets/animals/stone/animal_fox_stone.webp"
  },
  "panda": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_56_14 (2).png",
    "color": "assets/animals/color/animal_panda_color.webp",
    "stone": "assets/animals/stone/animal_panda_stone.webp"
  },
  "turtle": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_56_14 (3).png",
    "color": "assets/animals/color/animal_turtle_color.webp",
    "stone": "assets/animals/stone/animal_turtle_stone.webp"
  },
  "frog": {
    "status": "pair_ready",
    "source": "animal/ChatGPT Image 2026年8月6日 20_56_14 (4).png",
    "color": "assets/animals/color/animal_frog_color.webp",
    "stone": "assets/animals/stone/animal_frog_stone.webp"
  },
  "rhinoceros_beetle": {
    "status": "pair_ready",
    "source": "animal/animal_rhinoceros_beetle_color_source.png",
    "color": "assets/animals/color/animal_rhinoceros_beetle_color.webp",
    "stone": "assets/animals/stone/animal_rhinoceros_beetle_stone.webp"
  },
  "butterfly": {
    "status": "pair_ready",
    "source": "animal/animal_butterfly_color_source.png",
    "color": "assets/animals/color/animal_butterfly_color.webp",
    "stone": "assets/animals/stone/animal_butterfly_stone.webp"
  },
  "cat": {
    "status": "pair_ready",
    "source": "animal/animal_cat_color_source.png",
    "color": "assets/animals/color/animal_cat_color.webp",
    "stone": "assets/animals/stone/animal_cat_stone.webp"
  },
  "rabbit": {
    "status": "pair_ready",
    "source": "animal/animal_rabbit_color_source.png",
    "color": "assets/animals/color/animal_rabbit_color.webp",
    "stone": "assets/animals/stone/animal_rabbit_stone.webp"
  },
  "elephant": {
    "status": "pair_ready",
    "source": "animal/animal_elephant_color_source.png",
    "color": "assets/animals/color/animal_elephant_color.webp",
    "stone": "assets/animals/stone/animal_elephant_stone.webp"
  },
  "lion": {
    "status": "pair_ready",
    "source": "animal/animal_lion_color_source.png",
    "color": "assets/animals/color/animal_lion_color.webp",
    "stone": "assets/animals/stone/animal_lion_stone.webp"
  },
  "penguin": {
    "status": "pair_ready",
    "source": "animal/animal_penguin_color_source.png",
    "color": "assets/animals/color/animal_penguin_color.webp",
    "stone": "assets/animals/stone/animal_penguin_stone.webp"
  },
  "tuna": {
    "status": "pair_ready",
    "source": "animal/animal_tuna_color_source.png",
    "color": "assets/animals/color/animal_tuna_color.webp",
    "stone": "assets/animals/stone/animal_tuna_stone.webp"
  },
  "eel": {
    "status": "pair_ready",
    "source": "animal/animal_eel_color_source.png",
    "color": "assets/animals/color/animal_eel_color.webp",
    "stone": "assets/animals/stone/animal_eel_stone.webp"
  },
  "shark": {
    "status": "pair_ready",
    "source": "animal/animal_shark_color_source.png",
    "color": "assets/animals/color/animal_shark_color.webp",
    "stone": "assets/animals/stone/animal_shark_stone.webp"
  },
  "octopus": {
    "status": "pair_ready",
    "source": "animal/animal_octopus_color_source.png",
    "color": "assets/animals/color/animal_octopus_color.webp",
    "stone": "assets/animals/stone/animal_octopus_stone.webp"
  },
  "squid": {
    "status": "pair_ready",
    "source": "animal/animal_squid_color_source.png",
    "color": "assets/animals/color/animal_squid_color.webp",
    "stone": "assets/animals/stone/animal_squid_stone.webp"
  },
  "jellyfish": {
    "status": "pair_ready",
    "source": "animal/animal_jellyfish_color_source.png",
    "color": "assets/animals/color/animal_jellyfish_color.webp",
    "stone": "assets/animals/stone/animal_jellyfish_stone.webp"
  },
  "shrimp": {
    "status": "pair_ready",
    "source": "animal/animal_shrimp_color_source.png",
    "color": "assets/animals/color/animal_shrimp_color.webp",
    "stone": "assets/animals/stone/animal_shrimp_stone.webp"
  },
  "crab": {
    "status": "pair_ready",
    "source": "animal/animal_crab_color_source.png",
    "color": "assets/animals/color/animal_crab_color.webp",
    "stone": "assets/animals/stone/animal_crab_stone.webp"
  },
  "starfish": {
    "status": "pair_ready",
    "source": "animal/animal_starfish_color_source.png",
    "color": "assets/animals/color/animal_starfish_color.webp",
    "stone": "assets/animals/stone/animal_starfish_stone.webp"
  },
  "spotted_garden_eel": {
    "status": "pair_ready",
    "source": "animal/animal_spotted_garden_eel_color_source.png",
    "color": "assets/animals/color/animal_spotted_garden_eel_color.webp",
    "stone": "assets/animals/stone/animal_spotted_garden_eel_stone.webp"
  },
  "seahorse": {
    "status": "pair_ready",
    "source": "animal/animal_seahorse_color_source.png",
    "color": "assets/animals/color/animal_seahorse_color.webp",
    "stone": "assets/animals/stone/animal_seahorse_stone.webp"
  },
  "sunfish": {
    "status": "pair_ready",
    "source": "animal/animal_sunfish_color_source.png",
    "color": "assets/animals/color/animal_sunfish_color.webp",
    "stone": "assets/animals/stone/animal_sunfish_stone.webp"
  },
  "dolphin": {
    "status": "pair_ready",
    "source": "animal/animal_dolphin_color_source.png",
    "color": "assets/animals/color/animal_dolphin_color.webp",
    "stone": "assets/animals/stone/animal_dolphin_stone.webp"
  },
  "whale": {
    "status": "pair_ready",
    "source": "animal/animal_whale_color_source.png",
    "color": "assets/animals/color/animal_whale_color.webp",
    "stone": "assets/animals/stone/animal_whale_stone.webp"
  },
  "orca": {
    "status": "pair_ready",
    "source": "animal/animal_orca_color_source.png",
    "color": "assets/animals/color/animal_orca_color.webp",
    "stone": "assets/animals/stone/animal_orca_stone.webp"
  },
  "stag_beetle": {
    "status": "pair_ready",
    "source": "animal/animal_stag_beetle_color_source.png",
    "color": "assets/animals/color/animal_stag_beetle_color.webp",
    "stone": "assets/animals/stone/animal_stag_beetle_stone.webp"
  },
  "silkworm": {
    "status": "pair_ready",
    "source": "animal/animal_silkworm_color_source.png",
    "color": "assets/animals/color/animal_silkworm_color.webp",
    "stone": "assets/animals/stone/animal_silkworm_stone.webp"
  },
  "dragonfly": {
    "status": "pair_ready",
    "source": "animal/animal_dragonfly_color_source.png",
    "color": "assets/animals/color/animal_dragonfly_color.webp",
    "stone": "assets/animals/stone/animal_dragonfly_stone.webp"
  },
  "cicada": {
    "status": "pair_ready",
    "source": "animal/animal_cicada_color_source.png",
    "color": "assets/animals/color/animal_cicada_color.webp",
    "stone": "assets/animals/stone/animal_cicada_stone.webp"
  },
  "ant": {
    "status": "pair_ready",
    "source": "animal/animal_ant_color_source.png",
    "color": "assets/animals/color/animal_ant_color.webp",
    "stone": "assets/animals/stone/animal_ant_stone.webp"
  },
  "bee": {
    "status": "pair_ready",
    "source": "animal/animal_bee_color_source.png",
    "color": "assets/animals/color/animal_bee_color.webp",
    "stone": "assets/animals/stone/animal_bee_stone.webp"
  },
  "ladybug": {
    "status": "pair_ready",
    "source": "animal/animal_ladybug_color_source.png",
    "color": "assets/animals/color/animal_ladybug_color.webp",
    "stone": "assets/animals/stone/animal_ladybug_stone.webp"
  },
  "grasshopper": {
    "status": "pair_ready",
    "source": "animal/animal_grasshopper_color_source.png",
    "color": "assets/animals/color/animal_grasshopper_color.webp",
    "stone": "assets/animals/stone/animal_grasshopper_stone.webp"
  },
  "mantis": {
    "status": "pair_ready",
    "source": "animal/animal_mantis_color_source.png",
    "color": "assets/animals/color/animal_mantis_color.webp",
    "stone": "assets/animals/stone/animal_mantis_stone.webp"
  },
  "pill_bug": {
    "status": "pair_ready",
    "source": "animal/animal_pill_bug_color_source.png",
    "color": "assets/animals/color/animal_pill_bug_color.webp",
    "stone": "assets/animals/stone/animal_pill_bug_stone.webp"
  },
  "snail": {
    "status": "pair_ready",
    "source": "animal/animal_snail_color_source.png",
    "color": "assets/animals/color/animal_snail_color.webp",
    "stone": "assets/animals/stone/animal_snail_stone.webp"
  },
  "tadpole": {
    "status": "pair_ready",
    "source": "animal/animal_tadpole_color_source.png",
    "color": "assets/animals/color/animal_tadpole_color.webp",
    "stone": "assets/animals/stone/animal_tadpole_stone.webp"
  },
  "newt": {
    "status": "pair_ready",
    "source": "animal/animal_newt_color_source.png",
    "color": "assets/animals/color/animal_newt_color.webp",
    "stone": "assets/animals/stone/animal_newt_stone.webp"
  },
  "gecko": {
    "status": "pair_ready",
    "source": "animal/animal_gecko_color_source.png",
    "color": "assets/animals/color/animal_gecko_color.webp",
    "stone": "assets/animals/stone/animal_gecko_stone.webp"
  },
  "lizard": {
    "status": "pair_ready",
    "source": "animal/animal_lizard_color_source.png",
    "color": "assets/animals/color/animal_lizard_color.webp",
    "stone": "assets/animals/stone/animal_lizard_stone.webp"
  },
  "snake": {
    "status": "pair_ready",
    "source": "animal/animal_snake_color_source.png",
    "color": "assets/animals/color/animal_snake_color.webp",
    "stone": "assets/animals/stone/animal_snake_stone.webp"
  },
  "crocodile": {
    "status": "pair_ready",
    "source": "animal/animal_crocodile_color_source.png",
    "color": "assets/animals/color/animal_crocodile_color.webp",
    "stone": "assets/animals/stone/animal_crocodile_stone.webp"
  },
  "mammoth": {
    "status": "pair_ready",
    "source": "animal/animal_mammoth_color_source.png",
    "color": "assets/animals/color/animal_mammoth_color.webp",
    "stone": "assets/animals/stone/animal_mammoth_stone.webp"
  },
  "dodo": {
    "status": "pair_ready",
    "source": "animal/animal_dodo_color_source.png",
    "color": "assets/animals/color/animal_dodo_color.webp",
    "stone": "assets/animals/stone/animal_dodo_stone.webp"
  },
  "sabertooth": {
    "status": "pair_ready",
    "source": "animal/animal_sabertooth_color_source.png",
    "color": "assets/animals/color/animal_sabertooth_color.webp",
    "stone": "assets/animals/stone/animal_sabertooth_stone.webp"
  },
  "tyrannosaurus": {
    "status": "pair_ready",
    "source": "animal/animal_tyrannosaurus_color_source.png",
    "color": "assets/animals/color/animal_tyrannosaurus_color.webp",
    "stone": "assets/animals/stone/animal_tyrannosaurus_stone.webp"
  },
  "triceratops": {
    "status": "pair_ready",
    "source": "animal/animal_triceratops_color_source.png",
    "color": "assets/animals/color/animal_triceratops_color.webp",
    "stone": "assets/animals/stone/animal_triceratops_stone.webp"
  },
  "pteranodon": {
    "status": "pair_ready",
    "source": "animal/animal_pteranodon_color_source.png",
    "color": "assets/animals/color/animal_pteranodon_color.webp",
    "stone": "assets/animals/stone/animal_pteranodon_stone.webp"
  },
  "stegosaurus": {
    "status": "pair_ready",
    "source": "animal/animal_stegosaurus_color_source.png",
    "color": "assets/animals/color/animal_stegosaurus_color.webp",
    "stone": "assets/animals/stone/animal_stegosaurus_stone.webp"
  },
  "unicorn": {
    "status": "pair_ready",
    "source": "animal/animal_unicorn_color_source.png",
    "color": "assets/animals/color/animal_unicorn_color.webp",
    "stone": "assets/animals/stone/animal_unicorn_stone.webp"
  },
  "dragon": {
    "status": "pair_ready",
    "source": "animal/animal_dragon_color_source.png",
    "color": "assets/animals/color/animal_dragon_color.webp",
    "stone": "assets/animals/stone/animal_dragon_stone.webp"
  },
  "phoenix": {
    "status": "pair_ready",
    "source": "animal/animal_phoenix_color_source.png",
    "color": "assets/animals/color/animal_phoenix_color.webp",
    "stone": "assets/animals/stone/animal_phoenix_stone.webp"
  },
  "pegasus": {
    "status": "pair_ready",
    "source": "animal/animal_pegasus_color_source.png",
    "color": "assets/animals/color/animal_pegasus_color.webp",
    "stone": "assets/animals/stone/animal_pegasus_stone.webp"
  },
  "griffin": {
    "status": "pair_ready",
    "source": "animal/animal_griffin_color_source.png",
    "color": "assets/animals/color/animal_griffin_color.webp",
    "stone": "assets/animals/stone/animal_griffin_stone.webp"
  },
  "mermaid": {
    "status": "pair_ready",
    "source": "animal/animal_mermaid_color_source.png",
    "color": "assets/animals/color/animal_mermaid_color.webp",
    "stone": "assets/animals/stone/animal_mermaid_stone.webp"
  },
  "tsuchinoko": {
    "status": "pair_ready",
    "source": "animal/animal_tsuchinoko_color_source.png",
    "color": "assets/animals/color/animal_tsuchinoko_color.webp",
    "stone": "assets/animals/stone/animal_tsuchinoko_stone.webp"
  }
};
