/* Generated by tools/build-puzzle-bank.cjs. Do not hand-edit. */
(function (root) {
    "use strict";
    root.LIGHT_WINDOW_PUZZLES = Object.freeze([
  {
    "id": "t1-01",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ]
    ],
    "solution": [
      {
        "shape": "L3",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 1
      }
    ],
    "distractors": [],
    "solutionCount": 2,
    "difficultyScore": 42.31
  },
  {
    "id": "t1-02",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ]
    ],
    "solution": [
      {
        "shape": "T4",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "L3",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 43.01
  },
  {
    "id": "t1-03",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ]
    ],
    "solution": [
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 43.01
  },
  {
    "id": "t1-04",
    "tier": 1,
    "target": [
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 1
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 43.01
  },
  {
    "id": "t1-05",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 43.01
  },
  {
    "id": "t1-06",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ]
    ],
    "solution": [
      {
        "shape": "I2",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 2,
    "difficultyScore": 44.6
  },
  {
    "id": "t1-07",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 1
      }
    ],
    "distractors": [],
    "solutionCount": 2,
    "difficultyScore": 44.6
  },
  {
    "id": "t1-08",
    "tier": 1,
    "target": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": true,
        "x": 0,
        "y": 1
      },
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 45.3
  },
  {
    "id": "t1-09",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ]
    ],
    "solution": [
      {
        "shape": "I2",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 2
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 45.3
  },
  {
    "id": "t1-10",
    "tier": 1,
    "target": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ]
    ],
    "solution": [
      {
        "shape": "I2",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 1
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 48.5
  },
  {
    "id": "t2-01",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 1
      },
      {
        "shape": "L4",
        "rotation": 2,
        "flipped": true,
        "x": 0,
        "y": 0
      },
      {
        "shape": "I2",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 3
      }
    ],
    "distractors": [],
    "solutionCount": 6,
    "difficultyScore": 65.02
  },
  {
    "id": "t2-02",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ]
    ],
    "solution": [
      {
        "shape": "I4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "L4",
        "rotation": 3,
        "flipped": false,
        "x": 1,
        "y": 2
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 65.94
  },
  {
    "id": "t2-03",
    "tier": 2,
    "target": [
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        3,
        3
      ]
    ],
    "solution": [
      {
        "shape": "S4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "T4",
        "rotation": 3,
        "flipped": false,
        "x": 2,
        "y": 1
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 65.94
  },
  {
    "id": "t2-04",
    "tier": 2,
    "target": [
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ]
    ],
    "solution": [
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "I2",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.1
  },
  {
    "id": "t2-05",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ]
    ],
    "solution": [
      {
        "shape": "I4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 1
      },
      {
        "shape": "I2",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 3
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.1
  },
  {
    "id": "t2-06",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ]
    ],
    "solution": [
      {
        "shape": "I4",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 1
      },
      {
        "shape": "I3",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.1
  },
  {
    "id": "t2-07",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "solution": [
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": true,
        "x": 1,
        "y": 1
      },
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.39
  },
  {
    "id": "t2-08",
    "tier": 2,
    "target": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 0,
        "flipped": true,
        "x": 1,
        "y": 0
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 4
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.63
  },
  {
    "id": "t2-09",
    "tier": 2,
    "target": [
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 2
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 4
      }
    ],
    "distractors": [],
    "solutionCount": 1,
    "difficultyScore": 67.63
  },
  {
    "id": "t2-10",
    "tier": 2,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ]
    ],
    "solution": [
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "S4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "I2",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [],
    "solutionCount": 2,
    "difficultyScore": 67.82
  },
  {
    "id": "t3-01",
    "tier": 3,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ]
    ],
    "solution": [
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": true,
        "x": 0,
        "y": 0
      },
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 0
      }
    ],
    "distractors": [
      "O4"
    ],
    "solutionCount": 2,
    "difficultyScore": 92.68
  },
  {
    "id": "t3-02",
    "tier": 3,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ]
    ],
    "solution": [
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 2
      }
    ],
    "distractors": [
      "P5"
    ],
    "solutionCount": 2,
    "difficultyScore": 92.8
  },
  {
    "id": "t3-03",
    "tier": 3,
    "target": [
      [
        2,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 3
      },
      {
        "shape": "V5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 1
      }
    ],
    "distractors": [
      "L3"
    ],
    "solutionCount": 1,
    "difficultyScore": 93.38
  },
  {
    "id": "t3-04",
    "tier": 3,
    "target": [
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ]
    ],
    "solution": [
      {
        "shape": "P5",
        "rotation": 1,
        "flipped": true,
        "x": 0,
        "y": 1
      },
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 2
      }
    ],
    "distractors": [
      "T4"
    ],
    "solutionCount": 1,
    "difficultyScore": 93.73
  },
  {
    "id": "t3-05",
    "tier": 3,
    "target": [
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ]
    ],
    "solution": [
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 1
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      }
    ],
    "distractors": [
      "T4"
    ],
    "solutionCount": 2,
    "difficultyScore": 93.91
  },
  {
    "id": "t3-06",
    "tier": 3,
    "target": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        1,
        2
      ]
    ],
    "solution": [
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 1
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 0
      }
    ],
    "distractors": [
      "L4"
    ],
    "solutionCount": 2,
    "difficultyScore": 94.4
  },
  {
    "id": "t3-07",
    "tier": 3,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ]
    ],
    "solution": [
      {
        "shape": "W5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 3
      },
      {
        "shape": "L4",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [
      "V5"
    ],
    "solutionCount": 1,
    "difficultyScore": 94.61
  },
  {
    "id": "t3-08",
    "tier": 3,
    "target": [
      [
        1,
        0
      ],
      [
        3,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        0,
        4
      ],
      [
        0,
        5
      ]
    ],
    "solution": [
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": true,
        "x": 0,
        "y": 0
      },
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "V5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 3
      }
    ],
    "distractors": [
      "T4"
    ],
    "solutionCount": 1,
    "difficultyScore": 94.87
  },
  {
    "id": "t3-09",
    "tier": 3,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "solution": [
      {
        "shape": "W5",
        "rotation": 3,
        "flipped": false,
        "x": 1,
        "y": 1
      },
      {
        "shape": "L3",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 3
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [
      "O4"
    ],
    "solutionCount": 1,
    "difficultyScore": 95.63
  },
  {
    "id": "t3-10",
    "tier": 3,
    "target": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "solution": [
      {
        "shape": "W5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "I4",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "V5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      }
    ],
    "distractors": [
      "L3"
    ],
    "solutionCount": 1,
    "difficultyScore": 96.01
  },
  {
    "id": "t4-01",
    "tier": 4,
    "target": [
      [
        2,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ]
    ],
    "solution": [
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "L3",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 1
      },
      {
        "shape": "L5",
        "rotation": 3,
        "flipped": false,
        "x": 2,
        "y": 3
      },
      {
        "shape": "W5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      }
    ],
    "distractors": [
      "L4"
    ],
    "solutionCount": 7,
    "difficultyScore": 113.45
  },
  {
    "id": "t4-02",
    "tier": 4,
    "target": [
      [
        0,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 3,
        "flipped": true,
        "x": 0,
        "y": 0
      },
      {
        "shape": "T4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "W5",
        "rotation": 3,
        "flipped": false,
        "x": 3,
        "y": 1
      },
      {
        "shape": "P5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 2
      }
    ],
    "distractors": [
      "S4"
    ],
    "solutionCount": 4,
    "difficultyScore": 114.98
  },
  {
    "id": "t4-03",
    "tier": 4,
    "target": [
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ]
    ],
    "solution": [
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": true,
        "x": 2,
        "y": 0
      },
      {
        "shape": "S4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 1
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "T4",
        "rotation": 1,
        "flipped": false,
        "x": 4,
        "y": 1
      }
    ],
    "distractors": [
      "O4"
    ],
    "solutionCount": 2,
    "difficultyScore": 116.01
  },
  {
    "id": "t4-04",
    "tier": 4,
    "target": [
      [
        2,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 1,
        "flipped": false,
        "x": 5,
        "y": 2
      },
      {
        "shape": "V5",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 2
      },
      {
        "shape": "P5",
        "rotation": 3,
        "flipped": true,
        "x": 1,
        "y": 2
      },
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [
      "I4"
    ],
    "solutionCount": 2,
    "difficultyScore": 116.38
  },
  {
    "id": "t4-05",
    "tier": 4,
    "target": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ]
    ],
    "solution": [
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "L4",
        "rotation": 0,
        "flipped": true,
        "x": 3,
        "y": 1
      },
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": true,
        "x": 0,
        "y": 0
      },
      {
        "shape": "V5",
        "rotation": 1,
        "flipped": false,
        "x": 3,
        "y": 2
      }
    ],
    "distractors": [
      "I4"
    ],
    "solutionCount": 1,
    "difficultyScore": 116.56
  },
  {
    "id": "t4-06",
    "tier": 4,
    "target": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ]
    ],
    "solution": [
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 1,
        "y": 3
      },
      {
        "shape": "U5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 5
      },
      {
        "shape": "Z5",
        "rotation": 1,
        "flipped": true,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [
      "S4"
    ],
    "solutionCount": 2,
    "difficultyScore": 116.95
  },
  {
    "id": "t4-07",
    "tier": 4,
    "target": [
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        3,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ]
    ],
    "solution": [
      {
        "shape": "I3",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 4
      },
      {
        "shape": "Y5",
        "rotation": 1,
        "flipped": false,
        "x": 1,
        "y": 2
      },
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "U5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 2
      }
    ],
    "distractors": [
      "O4"
    ],
    "solutionCount": 1,
    "difficultyScore": 117.08
  },
  {
    "id": "t4-08",
    "tier": 4,
    "target": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        3,
        5
      ]
    ],
    "solution": [
      {
        "shape": "V5",
        "rotation": 3,
        "flipped": false,
        "x": 1,
        "y": 3
      },
      {
        "shape": "L3",
        "rotation": 2,
        "flipped": false,
        "x": 2,
        "y": 4
      },
      {
        "shape": "I4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      }
    ],
    "distractors": [
      "Y5"
    ],
    "solutionCount": 2,
    "difficultyScore": 117.6
  },
  {
    "id": "t4-09",
    "tier": 4,
    "target": [
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        6,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        6,
        2
      ],
      [
        6,
        3
      ]
    ],
    "solution": [
      {
        "shape": "Z5",
        "rotation": 1,
        "flipped": true,
        "x": 2,
        "y": 0
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 3,
        "y": 0
      },
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": false,
        "x": 5,
        "y": 1
      },
      {
        "shape": "Y5",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 1
      }
    ],
    "distractors": [
      "L3"
    ],
    "solutionCount": 1,
    "difficultyScore": 117.97
  },
  {
    "id": "t4-10",
    "tier": 4,
    "target": [
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        4,
        1
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        0,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ]
    ],
    "solution": [
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 3,
        "y": 2
      },
      {
        "shape": "U5",
        "rotation": 1,
        "flipped": false,
        "x": 3,
        "y": 0
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 5
      },
      {
        "shape": "T5",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 3
      }
    ],
    "distractors": [
      "I3"
    ],
    "solutionCount": 1,
    "difficultyScore": 119.93
  },
  {
    "id": "t5-01",
    "tier": 5,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ]
    ],
    "solution": [
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": true,
        "x": 1,
        "y": 2
      },
      {
        "shape": "T5",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "P5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": true,
        "x": 3,
        "y": 2
      }
    ],
    "distractors": [
      "O4",
      "W5"
    ],
    "solutionCount": 10,
    "difficultyScore": 143.04
  },
  {
    "id": "t5-02",
    "tier": 5,
    "target": [
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        6,
        0
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        6,
        1
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        6,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        6,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        1,
        5
      ]
    ],
    "solution": [
      {
        "shape": "V5",
        "rotation": 1,
        "flipped": false,
        "x": 4,
        "y": 2
      },
      {
        "shape": "Y5",
        "rotation": 1,
        "flipped": true,
        "x": 2,
        "y": 3
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 1
      },
      {
        "shape": "L4",
        "rotation": 1,
        "flipped": true,
        "x": 4,
        "y": 0
      },
      {
        "shape": "X5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 3
      }
    ],
    "distractors": [
      "U5",
      "I4"
    ],
    "solutionCount": 8,
    "difficultyScore": 144.44
  },
  {
    "id": "t5-03",
    "tier": 5,
    "target": [
      [
        3,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        0,
        6
      ]
    ],
    "solution": [
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": false,
        "x": 3,
        "y": 2
      },
      {
        "shape": "X5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "Y5",
        "rotation": 2,
        "flipped": false,
        "x": 1,
        "y": 2
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "T4",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 4
      }
    ],
    "distractors": [
      "V5",
      "I4"
    ],
    "solutionCount": 6,
    "difficultyScore": 145.15
  },
  {
    "id": "t5-04",
    "tier": 5,
    "target": [
      [
        0,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        0,
        5
      ]
    ],
    "solution": [
      {
        "shape": "T4",
        "rotation": 2,
        "flipped": false,
        "x": 2,
        "y": 2
      },
      {
        "shape": "S4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "T5",
        "rotation": 1,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "L5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 4
      },
      {
        "shape": "P5",
        "rotation": 0,
        "flipped": true,
        "x": 3,
        "y": 0
      }
    ],
    "distractors": [
      "X5",
      "U5"
    ],
    "solutionCount": 4,
    "difficultyScore": 146.55
  },
  {
    "id": "t5-05",
    "tier": 5,
    "target": [
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        2,
        5
      ]
    ],
    "solution": [
      {
        "shape": "S4",
        "rotation": 1,
        "flipped": true,
        "x": 2,
        "y": 3
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 1
      },
      {
        "shape": "T4",
        "rotation": 1,
        "flipped": false,
        "x": 4,
        "y": 1
      },
      {
        "shape": "L5",
        "rotation": 3,
        "flipped": false,
        "x": 1,
        "y": 0
      },
      {
        "shape": "X5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      }
    ],
    "distractors": [
      "U5",
      "I4"
    ],
    "solutionCount": 4,
    "difficultyScore": 146.93
  },
  {
    "id": "t5-06",
    "tier": 5,
    "target": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        0,
        4
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        2,
        6
      ],
      [
        3,
        6
      ],
      [
        4,
        6
      ],
      [
        3,
        7
      ]
    ],
    "solution": [
      {
        "shape": "P5",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 3
      },
      {
        "shape": "U5",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 3
      },
      {
        "shape": "T4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 6
      },
      {
        "shape": "X5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 3
      },
      {
        "shape": "V5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      }
    ],
    "distractors": [
      "I4",
      "L5"
    ],
    "solutionCount": 4,
    "difficultyScore": 147.53
  },
  {
    "id": "t5-07",
    "tier": 5,
    "target": [
      [
        0,
        0
      ],
      [
        1,
        0
      ],
      [
        2,
        0
      ],
      [
        3,
        0
      ],
      [
        4,
        0
      ],
      [
        5,
        0
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ]
    ],
    "solution": [
      {
        "shape": "X5",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "T5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 0
      },
      {
        "shape": "P5",
        "rotation": 2,
        "flipped": true,
        "x": 2,
        "y": 2
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 3
      },
      {
        "shape": "U5",
        "rotation": 1,
        "flipped": false,
        "x": 4,
        "y": 0
      }
    ],
    "distractors": [
      "S4",
      "W5"
    ],
    "solutionCount": 1,
    "difficultyScore": 147.63
  },
  {
    "id": "t5-08",
    "tier": 5,
    "target": [
      [
        5,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        1
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        5,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        5,
        3
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        7,
        4
      ],
      [
        4,
        5
      ]
    ],
    "solution": [
      {
        "shape": "W5",
        "rotation": 1,
        "flipped": false,
        "x": 3,
        "y": 0
      },
      {
        "shape": "V5",
        "rotation": 0,
        "flipped": false,
        "x": 5,
        "y": 2
      },
      {
        "shape": "L4",
        "rotation": 2,
        "flipped": false,
        "x": 3,
        "y": 3
      },
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": true,
        "x": 1,
        "y": 1
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 1
      }
    ],
    "distractors": [
      "T5",
      "Y5"
    ],
    "solutionCount": 3,
    "difficultyScore": 148.64
  },
  {
    "id": "t5-09",
    "tier": 5,
    "target": [
      [
        3,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        4,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        4,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        4
      ],
      [
        6,
        4
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        3,
        6
      ],
      [
        3,
        7
      ]
    ],
    "solution": [
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 2,
        "y": 2
      },
      {
        "shape": "T4",
        "rotation": 2,
        "flipped": false,
        "x": 2,
        "y": 0
      },
      {
        "shape": "Z5",
        "rotation": 0,
        "flipped": false,
        "x": 0,
        "y": 2
      },
      {
        "shape": "V5",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 2
      },
      {
        "shape": "Y5",
        "rotation": 0,
        "flipped": false,
        "x": 3,
        "y": 4
      }
    ],
    "distractors": [
      "L4",
      "X5"
    ],
    "solutionCount": 3,
    "difficultyScore": 149.33
  },
  {
    "id": "t5-10",
    "tier": 5,
    "target": [
      [
        4,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        1
      ],
      [
        4,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        2
      ],
      [
        3,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ],
      [
        3,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        4
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        0,
        5
      ],
      [
        1,
        5
      ],
      [
        2,
        5
      ],
      [
        3,
        5
      ],
      [
        4,
        5
      ],
      [
        5,
        5
      ],
      [
        0,
        6
      ],
      [
        4,
        6
      ],
      [
        5,
        6
      ]
    ],
    "solution": [
      {
        "shape": "L5",
        "rotation": 3,
        "flipped": false,
        "x": 0,
        "y": 5
      },
      {
        "shape": "O4",
        "rotation": 0,
        "flipped": false,
        "x": 4,
        "y": 5
      },
      {
        "shape": "I4",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 4
      },
      {
        "shape": "U5",
        "rotation": 0,
        "flipped": false,
        "x": 1,
        "y": 2
      },
      {
        "shape": "Z5",
        "rotation": 1,
        "flipped": false,
        "x": 2,
        "y": 0
      }
    ],
    "distractors": [
      "L4",
      "X5"
    ],
    "solutionCount": 1,
    "difficultyScore": 150.73
  }
]);
}(typeof globalThis !== "undefined" ? globalThis : this));
